name: PR - Check Pipeline
run-name: Running - ${{ github.event_name }}
on: [pull_request]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of code
        uses: actions/checkout@v4

      - name: Setup do JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build + Tests + Coverage + Lint
        run: mvn clean verify checkstyle:check pmd:check spotbugs:check